[versions]
agp = "9.3.1"
#Migrated to built-in kotlin. Make sure to change kotlin compose version here after upgrading AGP.
kotlinCompose = "2.4.10"
#Notice KSP version here.
ksp = "2.3.6"
coreKtx = "1.18.0"
#junit = "4.13.2"
#junitVersion = "1.1.5"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.13.0"
composeBom = "2026.06.01"
dnsjava = "3.6.5"
ipaddress = "5.6.2"
okhttp = "5.4.0"
gson = "2.14.0"
slf4j-android= "1.7.36"
room = "2.8.4"
lifecycleLivedataKtx = "2.10.0"
colorPicker = "0.7.0"
composeMaterialIconsCore = "1.7.8"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
#junit = { group = "junit", name = "junit", version.ref = "junit" }
#androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
#androidx-ui = { group = "androidx.compose.ui", name = "ui" }
#androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
#androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
#androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
#androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
#androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
dnsjava = { module = "dnsjava:dnsjava", version.ref = "dnsjava" }
ipaddress = { module = "com.github.seancfoley:ipaddress", version.ref = "ipaddress" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
compose-color-picker-android = { module = "com.godaddy.android.colorpicker:compose-color-picker-android", version.ref = "colorPicker" }
slf4j-android = { module = "org.slf4j:slf4j-android", version.ref = "slf4j-android" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx     = { module = "androidx.room:room-ktx",     version.ref = "room" }
room-compiler= { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
compose-material-icons-core = { group = "androidx.compose.material", name = "material-icons-core", version.ref = "composeMaterialIconsCore" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
#jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp                 = { id = "com.google.devtools.ksp",      version.ref = "ksp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlinCompose" }

